Internacionalização
ProgRS/CryptoMoedas pull request #5
Opened 2022-10-26 17:10 UTC by ProgRS

Foram gerados internacionalização para dois idiomas : inglês e o português
As traduções se referem as telas: “Inicial” , “Carteira”, “Movimentações”, ”Detalhes” e “Conversão”

2022-10-27 17:01 UTC, julialuciani requested changes

2022-10-27 17:01 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +        title:  Text(pageName),
Aqui também

2022-10-27 17:01 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +    String pageName = AppLocalizations.of(context)!.nameDetails;;
Aqui

2022-10-27 19:26 UTC, julialuciani commented on lib/pages/conversion.dart
> +    String pagename = AppLocalizations.of(context)!.nameCoinConvert;
Você pode colocar assim: 
final text = AppLocalization.of(context)!;

2022-10-27 19:26 UTC, julialuciani commented on lib/pages/conversion.dart
> +                    AppLocalizations.of(context)!.nameConvert,
Aqui você chamaria a variável do build:
text.nameConvert,

2022-10-27 20:03 UTC, ProgRS commented on lib/pages/conversion.dart
> +                    AppLocalizations.of(context)!.nameConvert,
Realizado os ajustes sugeridos

2022-10-27 20:04 UTC, ProgRS commented on lib/pages/conversion.dart
> +    String pagename = AppLocalizations.of(context)!.nameCoinConvert;
Realizado os ajustes sugeridos

2022-10-28 11:36 UTC, julialuciani commented on lib/pages/conversion.dart
> +    final pagename = AppLocalizations.of(context)!;
Talvez seria legal colocar sempre o mesmo nome para essa variável em todas as páginas. Algo que quem estiver lendo seu código vai tempre entender. Por exemplo text, textIntl, stringIntl (o que você achar melhor)

2022-10-28 11:36 UTC, julialuciani commented on lib/pages/conversion.dart
> +                    AppLocalizations.of(context)!.nameConvert,
Aqui a string poderia ser chamada com a sua variável que fica debaixo do buil com .nameConvert.
Ex: pagename.nameConvert, text.nameConvert, stringIntl.nameConvert.
O nome que fica antes do ponto não importa desde que seja o nome que você definiu para a variável

2022-10-28 11:36 UTC, julialuciani commented on lib/pages/conversion.dart
> +                            labelText: AppLocalizations.of(context)!.nameAmount),
Aqui é o mesmo esquema. Como o nome da sua variável é pagename seria pagename.nameAmount

2022-10-28 11:36 UTC, julialuciani commented on lib/pages/conversion.dart
> +                    AppLocalizations.of(context)!.nameConvertIn,
Aqui também

2022-10-28 11:36 UTC, julialuciani commented on lib/pages/conversion.dart
> +                          labelText: AppLocalizations.of(context)!.nameAmountAfter),
Com o . você pode acessar as propriedades da sua variável, por isso é tao fácil a substituição

2022-10-28 11:49 UTC, guilhermemaiawarren approved these changes
Minha sugestão envolve mais boas práticas para melhor leitura do código, se precisar de qualquer ajuda pode me chamar

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameCoin,
Da forma que você declarou pageName no começo da página, você poderia usar isso para tudo, então, eu sugiro mudar o nome da variável para algo mais entendível, como alguma das sugestões de nome que a Júlia deu. Nessa linha que eu marquei por exemplo, você colocaria (nome da variável).nameCoin e não precisaria estar chamando o AppLocalizations.of(context)! todas as vezes

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +    final pageName = AppLocalizations.of(context)!;
Apenas diria para mudar o nome

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameInfo,
Mesma coisa do comentário acima

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +                      subtitle: Text(AppLocalizations.of(context)!.nameActualValue),
Mesma coisa do comentário acima

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMarketCap,
Mesma coisa do comentário acima

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMinValue,
Mesma coisa do comentário acima

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMaxValue,
Mesma coisa do comentário acima

2022-10-28 11:49 UTC, guilhermemaiawarren commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameBtnConvert,
Mesma coisa do comentário acima

2022-10-28 13:36 UTC, julialuciani approved these changes

2022-10-28 13:36 UTC, julialuciani commented on lib/pages/conversion.dart
> +                        AppLocalizations.of(context)!.nameBtnCancel,
Falta só aqui

2022-10-28 13:36 UTC, julialuciani commented on lib/pages/conversion.dart
> +                      AppLocalizations.of(context)!.nameBtnConfirm,
Aqui

2022-10-28 13:36 UTC, julialuciani commented on lib/pages/navigation.dart
>  class Navigatio extends StatefulWidget {
Talvez aqui o nome deveria ser Navigation?

2022-10-31 13:27 UTC, CamileBarros approved these changes

2022-11-03 13:53 UTC, merged