Requisição API
ProgRS/CryptoMoedas pull request #6
Opened 2022-11-23 13:26 UTC by ProgRS

Implementação das requisição a API , destinada ao preenchimento da tela de "Detalhes"(utilizada a API da coinbase, visto a melhor instabilidade e limitação da requisição.)

2022-11-23 14:00 UTC, guilhermeqmaia commented on lib/models/coin.dart
>  class Moeda {
Só uma sugestão, manter o nome da classe igual ao nome do arquivo, nesse caso a classe seria Coin

2022-11-23 14:00 UTC, guilhermeqmaia commented on lib/repositories/coin_repository.dart
> +class MoedaRepository extends ChangeNotifier {
mesmo do comentário acima, CoinRepository

2022-11-23 14:00 UTC, guilhermeqmaia commented on lib/pages/carteiraApp.dart
> +  late MoedaRepository dolar = MoedaRepository();
um nome pode te ajudar na leitura do código quando tiver que alterar algo, coinRepository, por exemplo

2022-11-23 14:00 UTC, guilhermeqmaia commented on lib/repositories/coin_repository.dart
> +  Future<Moeda> PegarMoeda() async {
no dart o recomendado é que métodos iniciem com letra minúscula, pegarMoeda

2022-11-23 14:00 UTC, guilhermeqmaia commented on lib/repositories/coin_repository.dart
> +      precos.add(moeda['hour']);
adicionar um por vez pode causar um gasto de memória alto, acredito que tenha como fazer assim:
precos.addAll(moeda['hour'], moeda['day], etc)

2022-11-23 14:00 UTC, guilhermeqmaia reviewed
Verificar comentários

2022-11-23 14:08 UTC, guilhermeqmaia commented on lib/pages/carteiraApp.dart
> +            //
excluir comentario

2022-11-23 14:08 UTC, guilhermeqmaia commented on lib/pages/moedas_detalhes_page.dart
> -    //data = generateSpots(50)
excluir comentario

2022-11-23 16:00 UTC, vitor-mendes-warren commented on lib/pages/carteiraApp.dart
> +        FutureBuilder<List<Moeda>>(
**Sugestão**
Futurebuilder funcionar bem para tratar as requisições na view, mas acho que nos times eles utilizam um  FutureProvider
e na page carregam assim 

```
futureProviderCriado.when(
            data: (data) => Page()
                ),
            error: (e, r) => ErrorPage()
            loading: () => LoadingPage()
)
```

acho uma  boa ideia implementar desse jeito em outra oportunidade 👍

2022-11-23 16:06 UTC, vitor-mendes-warren commented on lib/repositories/coin_repository.dart
> +    final response = await http.get(Uri.parse(uri));
**Sugestão**
quando tiver oportunidade, testar requisições também com o [dio](https://pub.dev/packages/dio), mais completo e é utilizado nos times atualmente

2022-11-23 16:19 UTC, julialuciani requested changes

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
>            padding: const EdgeInsets.all(10.0),
Você tem um SizeBox ali sem altura, tenta tirar ele e vê se faz alguma diferença na tela. Senão fizer nada você pode remover. Além disso você tá usando uma DecoratedBox pois o próprio container tem o parâmetro "decoration". Basta remover a DecoratedBox, copiar o conteúdo de decoration dela e colocar no container.

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameCoin,
Por quê remover o text? Era ele que simplificava a intl do seu arquivo.

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameInfo,
Pode colocar o text de novo aqui

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMarketCap,
text

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +                          Text(AppLocalizations.of(context)!.nameActualValue),
mesmo do comentário acima

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMinValue,
Mesmo do comentário acima

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMaxValue,
text

2022-11-23 16:19 UTC, julialuciani commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameBtnConvert,
text

2022-11-30 01:38 UTC, ProgRS commented on lib/models/coin.dart
>  class Moeda {
Implementado as sugestões

2022-11-30 01:39 UTC, ProgRS commented on lib/pages/carteiraApp.dart
> +  late MoedaRepository dolar = MoedaRepository();
Implementado as sugestões

2022-11-30 01:39 UTC, ProgRS commented on lib/repositories/coin_repository.dart
> +  Future<Moeda> PegarMoeda() async {
Implementado as sugestões

2022-11-30 01:39 UTC, ProgRS commented on lib/repositories/coin_repository.dart
> +      precos.add(moeda['hour']);
Ajustado

2022-11-30 01:40 UTC, ProgRS commented on lib/pages/moedas_detalhes_page.dart
> -    //data = generateSpots(50)
Ajustado

2022-11-30 01:40 UTC, ProgRS commented on lib/main.dart
> +        create: (contex) => MoedaRepository(),
Implementado as sugestões

2022-11-30 01:40 UTC, ProgRS commented on lib/pages/carteiraApp.dart
> +    final carteira = AppLocalizations.of(context)!;
Implementado as sugestões

2022-11-30 01:40 UTC, ProgRS commented on lib/pages/carteiraApp.dart
> +    dolar = MoedaRepository();
Implementado as sugestões

2022-11-30 01:41 UTC, ProgRS commented on lib/pages/carteiraApp.dart
> +  late MoedaRepository dolar = MoedaRepository();
Ajustado

2022-11-30 01:41 UTC, ProgRS commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameBtnConvert,
Ajustado

2022-11-30 01:41 UTC, ProgRS commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMaxValue,
Implementado as sugestões

2022-11-30 01:41 UTC, ProgRS commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMinValue,
Ajustado

2022-11-30 01:42 UTC, ProgRS commented on lib/pages/moedas_detalhes_page.dart
> +                        AppLocalizations.of(context)!.nameMarketCap,
Ajustado

2022-11-30 01:42 UTC, ProgRS commented on lib/pages/moedas_detalhes_page.dart
> +                          Text(AppLocalizations.of(context)!.nameActualValue),
Implementado as sugestões

2022-11-30 11:53 UTC, guilhermeqmaia approved these changes

2022-11-30 12:22 UTC, julialuciani approved these changes

2022-12-08 13:47 UTC, merged